'store_id' => $aamarpay->store_id, //store id will be aamarpay,  contact integration@aamarpay.com for test/live id
                'amount' => Cart::total(), //transaction amount
                'payment_type' => 'VISA', //no need to change
                'currency' => 'BDT',  //currenct will be USD/BDT
                'tran_id' => rand(1111111,9999999), //transaction id must be unique from your end
                'cus_name' => $request->c_name,  //customer name
                'cus_email' => $request->c_email, //customer email address
                'cus_add1' => $request->c_address,  //customer address
                'cus_add2' => 'Mohakhali DOHS', //customer address
                'cus_city' => $request->c_city,  //customer city
                'cus_state' => 'Dhaka',  //state
                'cus_postcode' => $request->c_zipcode, //postcode or zipcode
                'cus_country' => $request->c_country,  //country
                'cus_phone' => $request->c_phone, //customer phone number
                'cus_fax' => $request->c_extra_phone,  //fax
                'ship_name' => 'ship name', //ship name
                'ship_add1' => 'House B-121, Road 21',  //ship address
                'ship_add2' => 'Mohakhali',
                'ship_city' => 'Dhaka',
                'ship_state' => 'Dhaka',
                'ship_postcode' => '1212',
                'ship_country' => 'Bangladesh',
                'desc' => 'payment description',
                'success_url' => route('success'), //your success route
                'fail_url' => route('fail'), //your fail route
                'cancel_url' => route('cancel'), //your cancel url
                'opt_a' => $request->c_country,  //subtotal
                'opt_b' => $request->c_city, //payment_type
                'opt_c' => $request->c_phone,  //customer phone
                'opt_d' => $request->c_address,
                'signature_key' => $aamarpay->signature_key);
